WITH popular_posts AS (
  SELECT reply_to_top
  FROM tg_comments.messages
  WHERE reply_to_top IS NOT NULL
  GROUP BY reply_to_top
  ORDER BY COUNT(*) DESC
  LIMIT 5
)
SELECT word, SUM(replies_count) AS total_replies_count
FROM (
  SELECT 
    TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(message, ' ', n.n), ' ', -1)) AS word, 
    COUNT(*) AS replies_count
  FROM 
    (SELECT 1 + a.N + b.N * 10 + c.N * 100 AS n
      FROM (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
      CROSS JOIN (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
      CROSS JOIN (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
      ORDER BY n
    ) n
  JOIN messages ON reply_to_top IN (SELECT reply_to_top FROM popular_posts)
  WHERE LENGTH(message) > 4 AND word <> ''
  AND (word LIKE '%[^[:alnum:]]%' OR word REGEXP '[a-zA-Z]')
  GROUP BY word
) AS words
GROUP BY word
ORDER BY total_replies_count DESC
